name: continuous integration
on:
  pull_request:
  push: { branches: master }
jobs:
  php_test:
    name: PHP Test
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        php-versions: ['7.4', '8.0', '8.1']
    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring, intl
        ini-values: post_max_size=256M, max_execution_time=180
        coverage: xdebug
        tools: php-cs-fixer
  docker_test:
    name: Build Docker Image Test
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: docker-compose.yaml
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build docker images
      run: docker-compose build
